volumes:
  postgres_data:

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app
    command: python -m src.interfaces.bot.main

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: uvicorn src.interfaces.api.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_fsm:
    image: redis:latest
    hostname: ${FSM_REDIS_HOST:-localhost}
    command: redis-server --requirepass "${FSM_REDIS_PASS:-}"
    env_file:
      - .env
    ports:
      - "6379:6379"
